"""Third Migration

Revision ID: 469e50fc71df
Revises: 1944776996b5
Create Date: 2020-06-13 19:22:14.093225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469e50fc71df'
down_revision = '1944776996b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
