"""Fourth Migration

Revision ID: eadac169c817
Revises: ac6e264fe9be
Create Date: 2020-06-19 12:13:51.287439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadac169c817'
down_revision = 'ac6e264fe9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_author', sa.String(), nullable=True))
    op.drop_column('blogs', 'blog_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_author')
    # ### end Alembic commands ###
